name: integration.app

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  PHARO_VERSION: 11

# Controls when the action will run. 
on:
  workflow_dispatch:
  push:
  pull_request:
  
jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest ]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3
      - uses: hpi-swa/setup-smalltalkCI@v1
        id: smalltalkci
        with:
          smalltalk-image: Pharo64-${{ env.PHARO_VERSION }}
      - name: Setup TeX Live
        uses: teatimeguest/setup-texlive-action@v2
        with:
          version: 2021
          packages: >-
            scheme-small
            latexmk
            luatex85
            ctablestack
            environ
            filehook
            fira
            fontaxes
            fontspec
            footmisc
            gentium-tug
            graphics
            hyphen-english
            import
            listings
            luatexbase
            memoir
            multirow
            opensans
            pgf
            polyglossia
            ragged2e
            tcolorbox
            tools
            trimspaces
            ulem
            varwidth
            xcolor
            xtab
            slantsc
      - name: go
        shell: bash
        timeout-minutes: 15
        run: |
          set -x
          echo "SMALLTALKCIBUILD: " ${SMALLTALK_CI_BUILD}
          echo "PWD: " `pwd`
          echo "ls: " `ls -a`
          mkdir -p ${SMALLTALK_CI_BUILD}/
          echo "ls: " `ls -a ${SMALLTALK_CI_BUILD}`
          cp -R archetypes ${SMALLTALK_CI_BUILD}/
          echo "ls: " `ls -a ${SMALLTALK_CI_BUILD}`
          smalltalkci -s  ${{ steps.smalltalkci.outputs.smalltalk-image }} .smalltalk.Integration.App.ston
      - name: debug
        run: |
          ls -l ${SMALLTALK_CI_BUILD}
          ls -l  ${SMALLTALK_CI_IMAGE}
          ls -l ${SMALLTALK_CI_CHANGES}
      - name: prepare upload
        run: |
          wget -O - get.pharo.org/64/${{ env.PHARO_VERSION }}0+vm | bash
          ./pharo Pharo.image metacello install file://${{ github.workspace }} BaselineOfPillarApp
          mv ${{ env.SMALLTALK_CI_CHANGES }} Pillar.changes
          mv ${{ env.SMALLTALK_CI_IMAGE }} Pillar.image
      - uses: actions/upload-artifact@v3
        if: matrix.platform == 'ubuntu-latest'
        with:
          name: Pillar image
          path: |
            Pillar.image
            Pillar.changes
            *.sources
 
