name: integration.app

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

# Controls when the action will run. 
on:
  workflow_dispatch:
  push:
  pull_request:
  
jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest ]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3
      - uses: hpi-swa/setup-smalltalkCI@v1
        id: smalltalkci
        with:
          smalltalk-image: Pharo64-11
      - name: go
        shell: bash
        timeout-minutes: 15
        run: |
          echo "SMALLTALKCIBUILD: " ${SMALLTALK_CI_BUILD}
          echo "PWD: " `pwd`
          echo "ls: " `ls -Ra`
          cp -r archetypes ${SMALLTALK_CI_BUILD}
          echo "ls: " `ls -Ra ${SMALLTALK_CI_BUILD}`
          smalltalkci -s  ${{ steps.smalltalkci.outputs.smalltalk-image }} .smalltalk.Integration.App.ston
      - name: DEBUG
        shell: bash
        timeout-minutes: 15
        run: tree ${SMALLTALK_CI_BUILD}
