name: publication

env:
  PHARO_VERSION: 11

# Controls when the action will run. 
on:
  workflow_dispatch:
  push:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: prepare upload
        run: |
          wget -O - get.pharo.org/64/${{ env.PHARO_VERSION }}0+vm | bash
          ./pharo Pharo.image eval --save "Metacello new repository: 'gitlocal://./src'; baseline: 'PillarApp'; load"
          target_dir=public/download
          mkdir -p $target_dir
          mv Pharo.changes $target_dir/Pillar.changes
          mv Pharo.image $target_dir/Pillar.image
          mv *.sources  $target_dir/
      - uses: actions/upload-artifact@v3
        with:
          name: Pillar image
          path: public/*
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v4
        with:
          build_dir: public
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
